name: conreality_map
description: >-
  A game map widget for Conreality games.
version: 0.0.1
author: Conreality.org <conreality@googlegroups.com>
homepage: https://github.com/conreality/conreality-widgets/tree/master/conreality_map

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.5.4-hotfix.2 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.19

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
