name: conreality_camera
description: >-
  An augmented-reality camera widget for Conreality games.
version: 0.0.1
author: Conreality.org <conreality@googlegroups.com>
homepage: https://github.com/conreality/conreality-widgets/tree/master/conreality_camera

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.5.4-hotfix.2 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.5.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
