# See: https://dart.dev/tools/pub/pubspec
name: conreality_fonts
version: 1.0.2
description: >-
  Font assets (in particular, the B612 font) for Conreality live-action games.
author: Conreality Team <conreality@googlegroups.com>
homepage: https://github.com/conreality/conreality-widgets/tree/master/conreality_fonts

environment:
  sdk: ">=2.4.0 <3.0.0"
  flutter: ">=1.7.8 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: B612
      fonts:
        - asset: fonts/b612/B612-Regular.ttf
          style: normal
        - asset: fonts/b612/B612-Italic.ttf
          style: italic
        - asset: fonts/b612/B612-Bold.ttf
          weight: 700
        - asset: fonts/b612/B612-BoldItalic.ttf
          weight: 700
          style: italic
    - family: B612Mono
      fonts:
        - asset: fonts/b612/B612Mono-Regular.ttf
          style: normal
        - asset: fonts/b612/B612Mono-Italic.ttf
          style: italic
        - asset: fonts/b612/B612Mono-Bold.ttf
          weight: 700
        - asset: fonts/b612/B612Mono-BoldItalic.ttf
          weight: 700
          style: italic
