# See: https://dart.dev/tools/pub/pubspec
name: conreality_joystick
version: 0.0.1
description: >-
  A joystick widget for robot control in Conreality live-action games.
author: Conreality Team <conreality@googlegroups.com>
homepage: https://github.com/conreality/conreality-widgets/tree/master/conreality_joystick

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.5.4-hotfix.2 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
