# See: https://dart.dev/tools/pub/pubspec
name: conreality_scene
version: 0.0.1
description: >-
  3D polygon mesh rendering widget for Conreality live-action games.
author: Conreality Team <conreality@googlegroups.com>
homepage: https://github.com/conreality/conreality-widgets/tree/master/conreality_scene

environment:
  sdk: ">=2.4.0 <3.0.0"
  flutter: ">=1.7.8 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
